import {
  pgTable,
  text,
  varchar,
  jsonb,
  timestamp,
  serial,
  integer,
  boolean,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// Better-Auth tables (generated by Better-Auth CLI)
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  companyName: text("company_name"),
  logoUrl: text("logo_url"),
  stripeCustomerId: text("stripe_customer_id"),
  subscriptionTier: text("subscription_tier")
    .default("free")
    .$type<"free" | "monthly" | "annual">(),
  subscriptionStatus: text("subscription_status").default("pending"),
  stripeSessionId: text("stripe_session_id"),
  estimatesThisMonth: integer("estimates_this_month").default(0).notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
);

// Better-Auth relations
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// Estimate table
export const estimates = pgTable("estimates", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(), // References Better-Auth's user.id
  title: varchar("title", { length: 255 }).notNull(),
  clientName: varchar("client_name", { length: 255 }).notNull(),
  clientPhone: varchar("client_phone", { length: 50 }),
  clientAddress: text("client_address"),
  items: jsonb("items").notNull().$type<
    Array<{
      description: string;
      quantity: number;
      unitPrice: number;
      type: "labor" | "material" | "equipment";
    }>
  >(),
  total: integer("total").notNull(), // Stored in cents
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Templates table for saved estimate templates (paid users only)
export const templates = pgTable("templates", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(), // References Better-Auth's user.id
  name: varchar("name", { length: 255 }).notNull(),
  equipmentCost: integer("equipment_cost").notNull(), // Stored in cents
  materialsCost: integer("materials_cost").notNull(), // Stored in cents
  laborHours: integer("labor_hours").notNull(),
  laborRate: integer("labor_rate").notNull(), // Stored in cents per hour
  discountPercent: integer("discount_percent").default(0).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Settings table (can be merged into users, but keeping separate for clarity)
export const settings = pgTable("settings", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().unique(), // References Better-Auth's user.id
  companyLogo: varchar("company_logo", { length: 500 }),
  companyName: varchar("company_name", { length: 255 }),
  pdfTemplate: varchar("pdf_template", { length: 500 }), // Path to PDF template file
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Custom table relations
export const estimatesRelations = relations(estimates, ({ one }) => ({
  user: one(user, {
    fields: [estimates.userId],
    references: [user.id],
  }),
}));

export const settingsRelations = relations(settings, ({ one }) => ({
  user: one(user, {
    fields: [settings.userId],
    references: [user.id],
  }),
}));

export const templatesRelations = relations(templates, ({ one }) => ({
  user: one(user, {
    fields: [templates.userId],
    references: [user.id],
  }),
}));

export type Estimate = typeof estimates.$inferSelect;
export type NewEstimate = typeof estimates.$inferInsert;
export type Settings = typeof settings.$inferSelect;
export type NewSettings = typeof settings.$inferInsert;
export type Template = typeof templates.$inferSelect;
export type NewTemplate = typeof templates.$inferInsert;
